# Generated by Django 6.0 on 2026-01-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('name', models.CharField(default='مجهول', max_length=120)),
                ('age', models.PositiveIntegerField(default=35)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('weight', models.FloatField(default=70)),
                ('height', models.FloatField(default=170)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('heavy', 'Heavy')], default='none', max_length=20)),
                ('exercise', models.FloatField(default=3)),
                ('diet_quality', models.PositiveIntegerField(default=5)),
                ('sleep_hours', models.FloatField(default=7)),
                ('stress_level', models.PositiveIntegerField(default=5)),
                ('family_diabetes', models.BooleanField(default=False)),
                ('family_heart', models.BooleanField(default=False)),
                ('family_cancer', models.BooleanField(default=False)),
                ('blood_pressure', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('high_1', 'High stage 1'), ('high_2', 'High stage 2'), ('unknown', 'Unknown')], default='normal', max_length=20)),
                ('cholesterol', models.CharField(choices=[('normal', 'Normal'), ('borderline', 'Borderline'), ('high', 'High'), ('unknown', 'Unknown')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
